CREATE TABLE IF NOT EXISTS `discord_bot`.`module_rodata_classes` (
	`id` INT NOT NULL,
	`slug` VARCHAR(45) NULL,
	`name` VARCHAR(45) NULL,
	PRIMARY KEY (`id`),
	UNIQUE INDEX `id_UNIQUE` (`id` ASC)
);

INSERT IGNORE INTO `discord_bot`.`module_rodata_jobclasses`
	(`id`,
	`slug`,
	`Name`)
	VALUES
		(0, 'novice', 'Novice'),
		(1,'swordman','Swordman'),
		(2,'magician','Magician'),
		(3,'archer','Archer'),
		(4,'acolyte','Acolyte'),
		(5,'merchant','Merchant'),
		(6,'thief','Thief'),
		(7,'knight','Knight'),
		(8,'priest','Priest'),
		(9,'wizard','Wizard'),
		(10,'blacksmith','Blacksmith'),
		(11,'hunter','Hunter'),
		(12,'assassin','Assassin'),
		(13,'knight_peco','Knight (Peco)'),
		(14,'crusader','Crusader'),
		(15,'monk','Monk'),
		(16,'sage','Sage'),
		(17,'rogue','Rogue'),
		(18,'alchemist','Alchemist'),
		(19,'bard','Bard'),
		(20,'dancer','Dancer'),
		(21,'crusader_peco','Crusader (Peco)'),
		(22,'wedding','Wedding'),
		(23,'super_novice','Super Novice'),
		(24,'gunslinger','Gunslinger'),
		(25,'ninja','Ninja'),
		(4001,'novice_high','Novice High'),
		(4002,'swordman_high','Swordman High'),
		(4003,'magician_high','Magician High'),
		(4004,'archer_high','Archer High'),
		(4005,'acolyte_high','Acolyte High'),
		(4006,'merchant_high','Merchant High'),
		(4007,'thief_high','Thief High'),
		(4008,'lord_knight','Lord Knight'),
		(4009,'high_priest','High Priest'),
		(4010,'high_wizard','High Wizard'),
		(4011,'whitesmith','Whitesmith'),
		(4012,'sniper','Sniper'),
		(4013,'assassin_cross','Assassin Cross'),
		(4014,'lord_knight_peco','Lord Knight (Peco)'),
		(4015,'paladin','Paladin'),
		(4016,'champion','Champion'),
		(4017,'professor','Professor'),
		(4018,'stalker','Stalker'),
		(4019,'creator','Creator'),
		(4020,'clown','Clown'),
		(4021,'gypsy','Gypsy'),
		(4022,'paladin_peco','Paladin (Peco)'),
		(4023,'baby_novice','Baby Novice'),
		(4024,'baby_swordman','Baby Swordman'),
		(4025,'baby_magician','Baby Magician'),
		(4026,'baby_archer','Baby Archer'),
		(4027,'baby_acolyte','Baby Acolyte'),
		(4028,'baby_merchant','Baby Merchant'),
		(4029,'baby_thief','Baby Thief'),
		(4030,'baby_knight','Baby Knight'),
		(4031,'baby_priest','Baby Priest'),
		(4032,'baby_wizard','Baby Wizard'),
		(4033,'baby_blacksmith','Baby Blacksmith'),
		(4034,'baby_hunter','Baby Hunter'),
		(4035,'baby_assassin','Baby Assassin'),
		(4036,'baby_knight_peco','Baby Knight (Peco)'),
		(4037,'baby_crusader','Baby Crusader'),
		(4038,'baby_monk','Baby Monk'),
		(4039,'baby_sage','Baby Sage'),
		(4040,'baby_rogue','Baby Rogue'),
		(4041,'baby_alchemist','Baby Alchemist'),
		(4042,'baby_bard','Baby Bard'),
		(4043,'baby_dancer','Baby Dancer'),
		(4044,'baby_crusader_peco','Baby Crusader (Peco)'),
		(4045,'baby_super_novice','Baby Super Novice'),
		(4046,'taekwon','Taekwon'),
		(4047,'star_gladiator','Star Gladiator'),
		(4048,'star_gladiator_union','Star Gladiator (Union)'),
		(4049,'soul_linker','Soul Linker');
